/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import com.tcs.tallerListas.beans.Estudiante;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;


public class IngresoEstudiantes {


	public static void main(String[] args) {
		ArrayList<Estudiante> estudianteArray = new ArrayList<Estudiante>();
		Proceso proceso = new Proceso();

		System.out.println("################ Ingreso de estudiantes ################");
		
		try {
			Scanner data = new Scanner(new File("src/main/resources/data.txt"));
			
			while (data.hasNextLine()) {

				String[] estData = data.nextLine().split(",");
				estudianteArray.add(new Estudiante(estData[0], estData[1], estData[2], estData[4], estData[3]));

			}
		} catch (FileNotFoundException e) {
			System.out.println("Error en la lectura del archivo" + e.getMessage());
		}

		System.out.println("El numero de estudiantes ingresados en el archivo es de: "+estudianteArray.size());
		System.out.println("/////////////////////////// \n");
		System.out.println("El numero de estudiantes entre 6 y 10 años es de "+ proceso.estudiantesEntre6y10(estudianteArray));
		System.out.println("/////////////////////////// \n");
		proceso.anadirPorGrado(estudianteArray);
		System.out.println("/////////////////////////// \n");
		proceso.imprimirDocumentoTI(estudianteArray);
		System.out.println("/////////////////////////// \n");
		proceso.imprimirRepitentes(estudianteArray);
	}

}
